# ESTO ES UN COMENTARIO
# Todo lo que está a la derecha de # es solo para nosotros

version: 0.3.2 # NO TOCAR

# Configuración Global
html:
  title: Links | Mi Nombre # Este es el Título que aparece en la pestaña de navegador

# Configuración Central
main:
  title: Mi Nombre # Aca podes poner tu nombre o el de tu producto

# Lista de bloques
blocks:
  # Estos bloques los podes editar cambiando SOLO el texto que está en blanco
  # Si querés eliminar una red social es tan facil como borrar los 3 campos correspondientes (title, icon, url)

  - title: LinkedIn # Este es el nombre del botón
    icon: linkedin # Este es el nombre del icono (si queres añadir una red social nueva, prestá atencion que es todo con minúscula)
    url: https://linkedin.com/in/TU-USUARIO # Link a donde redireccionará al hacer click

  - title: Github
    icon: github
    url: https://github.com/TU-USUARIO

  - title: Instagram
    icon: instagram
    url: https://www.instagram.com/lacryptaok/

  - title: Twitter
    icon: twitter
    url: https://twitter.com/TU-USUARIO

  - title: Sitio Web
    icon: url
    url: https://www.TU-WEB.com

  - title: Telegram
    icon: telegram
    url: https://t.me/TU-USUARIO
    
# Guardá el archivo haciendo click en Commit Changes, abajo
